name: CI

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build


  api-gateway:
    name: API Gateway CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api-gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: apps/api-gateway/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build


  ingestion-service:
    name: Ingestion Service CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/ingestion-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: services/ingestion-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build


  qa-service:
    name: QA Service CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/qa-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: services/qa-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build


  agent-orchestrator:
    name: Agent Orchestrator CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/agent-orchestrator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: services/agent-orchestrator/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build